name: paneDoors
version: 0.1
main: com.pobnellion.paneDoors.Main
api-version: 1.16
author: Bizink

commands:
  panedoor:
    description: Make a pane door where the player is looking
    usage: /panedoor [create | show | hide | delete | highlight | help]
    permission: panedoors.admin
    aliases: pd