name: paneDoors
version: 0.1
main: com.pobnellion.paneDoors.Main
api-version: 1.16
author: Bizink

commands:
  panedoor:
    description: Make a pane door where the player is looking
    usage: /panedoor [create | show | showall | hide | hideall | delete | help]
    permission: panedoors.makedoor
    aliases: pd